### ISSUE TITLE
Private mentions shown if bookmarked

### ISSUE THREAD

**Issue by p37307** [tonzyl/mastbookmarksrss#3]
It's worth noting that it also adds your private mentions to the RSS feed if you have bookmarked a private mention so you can quickly find it.

Would be nice to add a username and password to the script.

 Any plans or ideas on how to secure it from public?

Love the script, thanks for creating a tool like this.

**Comment by tonzyl** [comment]
Just a few random thoughts. 
I have no current plans to develop this. But you're right, if you know where the script is running and the name of the script, you could get the feed as an outsider too, and by extension any limited visibility mentions (the word private is misleading here I think, it's just another post, just not broadcasted to all followers, but not secure/private at all). 

There are a few ways to increase security by obscurity that come to mind though.
- give the script a random name
- host the script on an otherwise not (obviously) used domain name
- perhaps have the script fetch the API token from a location that is itself secured, as opposed to having it in the script.

Or separate it from the general world outside:
- place it where the feed reader can reach but not the outside world (e.g. shielded folder outside the www folder, or on localhost for a local feed reader ).
